import Head from 'next/head';
import { Footer, Form, Header, Hero, Services } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Hero />
        <Services />
        <Form />
      </main>
      <Footer />
    </>
  );
}
